# Generated by Django 5.1.4 on 2025-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(related_name='fornecedores', to='estoque.produto'),
        ),
    ]
