# Generated by Django 5.1.4 on 2025-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_fornecedor_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedores',
            field=models.ManyToManyField(related_name='produtos', to='estoque.fornecedor'),
        ),
    ]
