# Generated by Django 5.1.4 on 2025-01-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_fornecedor_produtos_produto_fornecedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
