# Generated by Django 5.1.4 on 2025-01-07 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_id_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
